spring.application.name=ssl
server.port=8443

server.ssl.key-store=classpath:localhost.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=changeit

server.ssl.protocol=TLS
server.ssl.enabled-protocols=TLSv1.2
server.ssl.ciphers=TLS_RSA_WITH_AES_256_CBC_SHA256, TLS_RSA_WITH_AES_256_CBC_SHA

casdoor.endpoint=https://localhost:8445
casdoor.client-id=87cde7d40fe8298806d4
casdoor.client-secret=14c50f2129548620eaf50982ef1eb95a1c315ca0
casdoor.redirect-uri=https://localhost:8443/callback
casdoor.app-name=lab3
casdoor.org-name=built-in